apiVersion: apps/v1
kind: Deployment
metadata:
  name: drinkool-frontend
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: gitea-registry-secret 
      containers:
      - name: frontend-container
        image: git.demonkernel.io.vn/foodsurf/frontend:latest
        resources:
          limits:
            cpu: "50m"  
            memory: "32Mi" 
          requests:
            cpu: "10m" 
            memory: "16Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  type: NodePort 
  selector:
    app: web 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080